// <auto-generated />
using System;
using Hotel1.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.2-servicing-10034");

            modelBuilder.Entity("Hotel1.Entity.Cuartos", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("NumeroHabitacion")
                        .IsRequired();

                    b.Property<int>("StatusId");

                    b.Property<int>("TipoDeCuartoId");

                    b.HasKey("Id");

                    b.HasIndex("StatusId");

                    b.HasIndex("TipoDeCuartoId");

                    b.ToTable("Cuartos");
                });

            modelBuilder.Entity("Hotel1.Entity.Reservas", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("CantidadPersonas");

                    b.Property<int>("CuartoId");

                    b.Property<int>("DiasReserva");

                    b.Property<DateTime>("FechaReserva");

                    b.Property<int>("IdentificacionCliente");

                    b.Property<string>("NombreCliente")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CuartoId");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("Hotel1.Entity.Status", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descripcion")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Status");
                });

            modelBuilder.Entity("Hotel1.Entity.TipoDeCuarto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("descripcion")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("TipoDeCuartos");
                });

            modelBuilder.Entity("Hotel1.Entity.Cuartos", b =>
                {
                    b.HasOne("Hotel1.Entity.Status", "Status")
                        .WithMany("Cuartos")
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Hotel1.Entity.TipoDeCuarto", "TipoDeCuarto")
                        .WithMany("Cuartos")
                        .HasForeignKey("TipoDeCuartoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Hotel1.Entity.Reservas", b =>
                {
                    b.HasOne("Hotel1.Entity.Cuartos", "Cuartos")
                        .WithMany("Reservas")
                        .HasForeignKey("CuartoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
